### ISSUE TITLE
Document Contributing to Test Suite

### ISSUE THREAD

**Issue by ravenmaster001** [uccser/cs-unplugged#189] opened 2017-04-12 00:07 UTC
Add issues as seen:

- [ ] Use of tags
- [ ] Location of tests
- [ ] White box vs. Black box testing
- [ ] Independent testing

**Comment by JackMorganNZ** [comment] 2017-05-21 08:40
Duplicate of #178.

**Closed by JackMorganNZ** 2017-05-21 08:40 UTC
Labels: documentation
